[workspace]
members = ["contracts/*", "packages/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/nymlab/vectis-ssi"
keywords = [ "Vectis", "CosmWasm", "zkp", "verifiableCredential" ]

[workspace.dependencies]
cosmwasm-schema = "1.2.5"
cosmwasm-std = { version =  "1.2.5", features = ["cosmwasm_1_2", "ibc3"]}
cw-storage-plus = "1.1"
cw2 = "1.0"
thiserror = "1"
sylvia = "0.7.0"
sylvia-derive = "0.7.0"
cw-multi-test = "0.16"
anyhow = { version = "1.0.51"}
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-wasm = "0.5.1"
ursa = { git = "https://github.com/whalelephant/ursa", default-features = false, features = ["cl_onchain", "serde"], version = "0.3.7", rev = "7cdccf35fb1a0"}
schemars = "0.8.1"

[profile.release]
codegen-units = 1
incremental = false
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
